version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands: []
  pre_build:
    commands: []
  build:
    commands: []
  post_build:
    commands: []

artifacts:
  files:
    - '**/*'
  base-directory: content
